enum UIAction {
  OPEN_DRAWER = "/UIAction/OPEN_DRAWER",
  CLOSE_DRAWER = "/UIAction/CLOSE_DRAWER",
  SHOW_MODAL = "/UIAction/SHOW_MODAL",
  HIDE_MODAL = "/UIAction/HIDE_MODAL",
  SHOW_SNACKBAR = "/UIAction/SHOW_SNACKBAR",
  HIDE_SNACKBAR = "/UIAction/HIDE_SNACKBAR",
  ADD_POPUP = "/UIAction/ADD_POPUP",
  REMOVE_POPUP = "/UIAction/REMOVE_POPUP",
  ADD_TOAST = "/UIAction/ADD_TOAST",
  REMOVE_TOAST = "/UIAction/REMOVE_TOAST"
}

export { UIAction };